O3-2395: Add documentation for enabling traces in E2E tests
denniskigen/o3-docs pull request #9
Opened 2023-09-04 18:40 UTC by DilshanNaveen

2023-09-04 18:40 UTC, DilshanNaveen commented
@jayasanka-sack

2023-09-04 18:49 UTC, denniskigen commented on pages/docs/frontend-modules/testing.mdx
> +#### Accessing Traces
```suggestion
### Accessing Traces
```

2023-09-05 06:15 UTC, jayasanka-sack requested changes
Thank you for your PR, @DilshanNaveen. We appreciate your efforts. For this section, we're focusing on how to view traces rather than their configuration. It would be great if you could integrate this guide under this heading: https://o3-docs.openmrs.org/docs/frontend-modules/testing#view-test-reports-from-github-actions--bamboo. Could you kindly make this adjustment? Thanks again!

2023-09-05 16:44 UTC, DilshanNaveen commented
Dear @jayasanka-sack, thank you for your review and your feedback, are you asking me to ditch the configuration part and keep the accessing traces part under View test reports from GitHub Actions / Bamboo section?

2023-09-05 17:10 UTC, jayasanka-sack approved these changes
Thanks @DilshanNaveen ! This is exactly what is needed.

2023-09-05 17:11 UTC, merged